# Generated by Django 5.1.6 on 2025-06-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0022_bankaccountmodel_financial_institution_and_more'),
        ('django_ledger', '0040_remove_journalentrymodel_fund_and_more'),
    ]

    operations = [
    ]
